#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

yarn lint-staged

poetry shell
poetry run isort api
poetry run black api
poetry export -f requirements.txt --output requirements.txt --without-hashes
