name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run TypeScript type check
        run: yarn type-check

      - name: Run TypeScript lint
        run: yarn lint

      - uses: pre-commit/action@v3.0.0
        name: 'Run pre-commit checks'
        with:
          extra_args: --all-files --show-diff-on-failure

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5

      - name: Run unit tests
        run: yarn test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
