name: Check PR

on: [pull_request]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - name: tweak deploy permission
        run: git config --global --add safe.directory /tmp/tmp.*

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Install dependencies (with cache)
      #   uses: bahmutov/npm-install@v1

      # - name: Check types
      #   run: yarn type-check

      # - name: Check linting
      #   run: yarn lint

      # - name: Check commits messages
      #   uses: wagoid/commitlint-github-action@v4

      - name: Trigger vercel deployment
        uses: datalbry/copy_folder_to_another_repo_action@1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: './'
          destination_repo: 'aorumbayev/aw-swapper-releases'
          user_email: 'info@algoworld.io'
          user_name: 'AlgoWorld Bot'
          destination_branch: 'releases'
          commit_msg: '[AW_RELEASE] New deploy trigger'
