name: Check PR

on: [pull_request]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Install dependencies (with cache)
      #   uses: bahmutov/npm-install@v1

      # - name: Check types
      #   run: yarn type-check

      # - name: Check linting
      #   run: yarn lint

      # - name: Check commits messages
      #   uses: wagoid/commitlint-github-action@v4

      - name: Trigger release
        run: |
           git config --global user.email "info@algoworld.io"
           git config --global user.name "AlgoWorld Bot"
           git clone --quiet --branch=releases https://${{ secrets.API_TOKEN_GITHUB }}@github.com/aorumbayev/aw-swapper-releases /tmp/releases > /dev/null
           cd /tmp/releases
           git add -f .
           git commit -m "New release trigger 🤖"
           git push -fq origin releases > /dev/null
