name: E2E Tests
on:
  pull_request:
    branches: [main]
jobs:
  e2e_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Expose e2e base url
        run: |
          echo ::set-env name=PR_CNT::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo ::set-env name=E2E_TESTS_BASE_URL::${{ format('https://pr-/{0}.vercel-action.millionalgos.com', $PR_CNT) }}
          echo $E2E_TESTS_BASE_URL
        shell: bash

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Deploy preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_STAGING_PROJECT_ID}} #Required
          working-directory: ./
          alias-domains: |
            pr-{{PR_NUMBER}}.vercel-action.millionalgos.com

      - name: Run Playwright tests
        run: |
          E2E_TESTS_BASE_URL=${{ format('https://pr-/{0}.vercel-action.millionalgos.com', secrets.PR_NUMBER) }} yarn run test:e2e:ci

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
