name: E2E Tests
on:
  pull_request:
    branches: [main]
jobs:
  e2e_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run Playwright tests
        env:
          E2E_TESTS_BOB_MNEMONIC: ${{ secrets.E2E_TESTS_BOB_MNEMONIC }}
          E2E_TESTS_ALICE_MNEMONIC: ${{ secrets.E2E_TESTS_ALICE_MNEMONIC }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: DEBUG=pw:api yarn run test:e2e:ci:local

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
